<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Telegram.Bot.dll" />
    <None Remove="Telegram.Bot.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Telegram.Bot.dll" />
    <Content Include="Telegram.Bot.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataLayer\DataLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Telegram.Bot">
      <HintPath>..\BeyabBot\Telegram.Bot.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
